CREATE TABLE EMPLOYEE (
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    FIRSTNAME VARCHAR(25),
    LASTNAME VARCHAR(25),
    DEPARTMENT_ID INTEGER NOT NULL,
    PRIMARY KEY (EMAIL)
);

CREATE TABLE DEPARTMENT (
    DEPARTMENT_ID INTEGER NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    PRIMARY KEY (DEPARTMENT_ID)
);

CREATE TABLE IDENTIFIER (
   TABLE_NAME VARCHAR(100) NOT NULL,
   CURRENT_VALUE INTEGER DEFAULT 1 NOT NULL,
   PRIMARY KEY (TABLE_NAME)
);
