CREATE TABLE EMPLOYEE (
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    FIRSTNAME VARCHAR(25),
    LASTNAME VARCHAR(25),
    DEPARTMENT_ID INTEGER NOT NULL,
    PRIMARY KEY (EMAIL)
);

CREATE TABLE DEPARTMENT (
    DEPARTMENT_ID INTEGER NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    PRIMARY KEY (DEPARTMENT_ID)
);